import type { ComponentType } from "react";
import {
  SiAlgolia,
  SiAnthropic,
  SiApachekafka,
  SiArgo,
  SiChatbot,
  SiClaude,
  SiCrewai,
  SiCursor,
  SiDocker,
  SiElasticsearch,
  SiEslint,
  SiFastapi,
  SiGit,
  SiGithubactions,
  SiGithubcopilot,
  SiGitlab,
  SiGrafana,
  SiHelm,
  SiHuggingface,
  SiJira,
  SiKubernetes,
  SiLangchain,
  SiLanggraph,
  SiMilvus,
  SiMlflow,
  SiMockserviceworker,
  SiModelcontextprotocol,
  SiMui,
  SiNeo4j,
  SiNextdotjs,
  SiNumpy,
  SiOpenrouter,
  SiOpentelemetry,
  SiPandas,
  SiPostgresql,
  SiPrometheus,
  SiPytest,
  SiPytorch,
  SiPython,
  SiReact,
  SiRedis,
  SiRedux,
  SiRuff,
  SiScikitlearn,
  SiSonarqubeserver,
  SiSpringboot,
  SiSqlalchemy,
  SiTerraform,
  SiTestinglibrary,
  SiTypescript,
  SiVite,
  SiVitest,
  SiWindsurf,
  SiZap,
} from "@icons-pack/react-simple-icons";

type IconComponent = ComponentType<{ size?: number; color?: string }>;

const icons: Record<string, IconComponent> = {
  algolia: SiAlgolia,
  anthropic: SiAnthropic,
  apachekafka: SiApachekafka,
  argo: SiArgo,
  chatbot: SiChatbot,
  claude: SiClaude,
  crewai: SiCrewai,
  cursor: SiCursor,
  docker: SiDocker,
  elasticsearch: SiElasticsearch,
  eslint: SiEslint,
  fastapi: SiFastapi,
  git: SiGit,
  githubactions: SiGithubactions,
  githubcopilot: SiGithubcopilot,
  gitlab: SiGitlab,
  grafana: SiGrafana,
  helm: SiHelm,
  huggingface: SiHuggingface,
  jira: SiJira,
  kubernetes: SiKubernetes,
  langchain: SiLangchain,
  langgraph: SiLanggraph,
  milvus: SiMilvus,
  mlflow: SiMlflow,
  mockserviceworker: SiMockserviceworker,
  modelcontextprotocol: SiModelcontextprotocol,
  mui: SiMui,
  neo4j: SiNeo4j,
  nextdotjs: SiNextdotjs,
  numpy: SiNumpy,
  openrouter: SiOpenrouter,
  opentelemetry: SiOpentelemetry,
  pandas: SiPandas,
  postgresql: SiPostgresql,
  prometheus: SiPrometheus,
  pytest: SiPytest,
  pytorch: SiPytorch,
  python: SiPython,
  react: SiReact,
  redis: SiRedis,
  redux: SiRedux,
  ruff: SiRuff,
  scikitlearn: SiScikitlearn,
  sonarqube: SiSonarqubeserver,
  springboot: SiSpringboot,
  sqlalchemy: SiSqlalchemy,
  terraform: SiTerraform,
  testinglibrary: SiTestinglibrary,
  typescript: SiTypescript,
  vite: SiVite,
  vitest: SiVitest,
  windsurf: SiWindsurf,
  zap: SiZap,
};

export function TechIcon({ slug, size = 16 }: { slug?: string; size?: number }) {
  const Icon = slug ? icons[slug] : undefined;
  if (!Icon) {
    return (
      <span className="text-cyan-400" style={{ fontSize: size - 2 }} aria-hidden>
        ✦
      </span>
    );
  }
  return <Icon size={size} color="default" />;
}
